github_token    = "YOUR_GITHUB_PERSONAL_ACCESS_TOKEN"
github_username = "YOUR_GITHUB_USERNAME"
repo_name       = "NAME_OF_THE_REPOSITORY_TO_CLONE"
db_username     = "YOUR_DATABASE_USERNAME"
db_password     = "YOUR_DATABASE_PASSWORD"
